name: shelf_example
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  args: ^1.6.0
  mustache_template: ^2.0.0
  shelf: ^1.0.0
  logging: ^1.0.0
  path: ^1.8.0
  shelf_static: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0
